export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:slug',
  CATEGORY: '/categories/:slug',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  PROFILE: '/profile',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_USERS: '/admin/users',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_SITE_CONTENT: '/admin/site-content',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_BRANDS: '/admin/brands',
  ADMIN_SITE_SETTINGS: '/admin/site-settings',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_DETAIL: '/admin/products/:slug',
  ADMIN_ORDERS: '/admin/orders',
} as const;

